# Generated by Django 3.0.6 on 2020-06-09 15:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import moviesapp.movies.validators


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(error_messages={'invalid': 'Movie with this Title already exists.'}, max_length=255, unique=True, validators=[moviesapp.movies.validators.validate_title], verbose_name="Movie's title"),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.Movie')),
            ],
        ),
    ]
